### ISSUE TITLE
Indexing not working

### ISSUE THREAD

**Issue by Pro-procrastinator** [saadaminj/Information-Retrieval-CitationAS-Summary-Generator#1]
I am trying to run the program, but it's giving an error of the data directory not found and data.npz file not found. I try to debug it and found that it is not moving forward where you are making vectors from terms ( line 178 CItationAS.py). 

![image](https://user-images.githubusercontent.com/55623734/168475067-39216af0-9b58-4f85-b7d3-359d116490d2.png)

**Comment by saadaminj** [comment]
Hey, I have just uploaded jupyter notebook file, try to run that notebook in anaconda jupyter notebook, and check paths in both the notebook and the previous file you are trying to run, I have uploaded data folder and data.npz before too.

**Comment by Pro-procrastinator** [comment]
Thanks for response, do have any gold queries ?
